# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.2.1
          poetry install

      - name: Check with isort
        run: poetry run isort isort openapi_fastapi_client --check-only

      - name: Lint with black
        run: poetry run black openapi_fastapi_client --check

      - name: Test with pytest
        run: poetry run pytest tests
